# settings SobekGraph
DEFAULT_MAJOR_GRID_X_AXIS_VISIBLE = True
DEFAULT_MINOR_GRID_X_AXIS_VISIBLE = False
DEFAULT_MAJOR_GRID_Y_AXIS_VISIBLE = True
DEFAULT_MINOR_GRID_Y_AXIS_VISIBLE = False

LINEWIDTH_MAJOR_GRID = 1
LINEWIDTH_MINOR_GRID = 0.2

ANGLE_TICK_LABELS_X_AXIS = 90