"""Module using sobekboundary.py to add boundaries to a Sobek model"""

import datetime
import math

import sobekboundary as sobbnd

bnd_path = r"N:\Sobek213\PyTls.lit\WORK\BOUNDARY.DAT"


# EXAMPLE 1: writing Sobek boundary using data generated by this script:

# generate list with datetime values for timeseries:
timestep = datetime.timedelta(seconds=60*10)
number_of_timesteps = int(24*60/10)
start_date = datetime.datetime(year=2020, month=4, day=15)
time_series_dates = [start_date + timestep * n for n in range(number_of_timesteps)]

# generate list of discharges using sine for timeseries:
discharges = [math.sin(n/number_of_timesteps * math.pi) for n in range(number_of_timesteps)]

# generate string Sobek timeseries:
str_sobek_timeseries = sobbnd.return_str_sobek_boundary_timeseries_from_lists(node_id='bnd_bov',
                                                                              sobek_function_type=sobbnd.LINEAR,
                                                                              sobek_value_type=sobbnd.Q,
                                                                              lst_datetime=time_series_dates,
                                                                              lst_values=discharges)

# Write string Sobek timeseries to Sobek boundary file:
sobbnd.add_or_replace_timeseries_bnd_file(bnd_path, str_sobek_timeseries)


# EXAMPLE 2: writing Sobek boundary using Excel data:
xls_path = r"data_for_examples\Excel\bnd.xlsx"

# generate string Sobek timeseries:
str_time_series = sobbnd.return_str_sobek_boundary_timeseries_from_excel(node_id="bnd_bov",
                                                                         sobek_function_type=sobbnd.LINEAR,
                                                                         sobek_value_type=sobbnd.Q,
                                                                         xls_path=xls_path,
                                                                         sheet_name="blad_bnd",
                                                                         column_values=2,
                                                                         headers=True)
# Write string Sobek timeseries to Sobek boundary file:
sobbnd.add_or_replace_timeseries_bnd_file(bnd_path, str_time_series)
